//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppCliente_WebServiceIUT.ServiceCRUD {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceCRUD.ICRUD")]
    public interface ICRUD {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICRUD/AddDepartment", ReplyAction="http://tempuri.org/ICRUD/AddDepartmentResponse")]
        bool AddDepartment(string departmentName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICRUD/AddDepartment", ReplyAction="http://tempuri.org/ICRUD/AddDepartmentResponse")]
        System.Threading.Tasks.Task<bool> AddDepartmentAsync(string departmentName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICRUD/AddPromo", ReplyAction="http://tempuri.org/ICRUD/AddPromoResponse")]
        void AddPromo(string promoName, string promoDept);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICRUD/AddPromo", ReplyAction="http://tempuri.org/ICRUD/AddPromoResponse")]
        System.Threading.Tasks.Task AddPromoAsync(string promoName, string promoDept);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICRUD/AddStudent", ReplyAction="http://tempuri.org/ICRUD/AddStudentResponse")]
        void AddStudent(string studentFirstName, string studentLastName, System.DateTime studentBirthDate, string promoName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICRUD/AddStudent", ReplyAction="http://tempuri.org/ICRUD/AddStudentResponse")]
        System.Threading.Tasks.Task AddStudentAsync(string studentFirstName, string studentLastName, System.DateTime studentBirthDate, string promoName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICRUD/UpdatePromoLists", ReplyAction="http://tempuri.org/ICRUD/UpdatePromoListsResponse")]
        string[] UpdatePromoLists();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICRUD/UpdatePromoLists", ReplyAction="http://tempuri.org/ICRUD/UpdatePromoListsResponse")]
        System.Threading.Tasks.Task<string[]> UpdatePromoListsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICRUD/UpdateDeptLists", ReplyAction="http://tempuri.org/ICRUD/UpdateDeptListsResponse")]
        string[] UpdateDeptLists();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICRUD/UpdateDeptLists", ReplyAction="http://tempuri.org/ICRUD/UpdateDeptListsResponse")]
        System.Threading.Tasks.Task<string[]> UpdateDeptListsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICRUDChannel : AppCliente_WebServiceIUT.ServiceCRUD.ICRUD, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CRUDClient : System.ServiceModel.ClientBase<AppCliente_WebServiceIUT.ServiceCRUD.ICRUD>, AppCliente_WebServiceIUT.ServiceCRUD.ICRUD {
        
        public CRUDClient() {
        }
        
        public CRUDClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CRUDClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CRUDClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CRUDClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool AddDepartment(string departmentName) {
            return base.Channel.AddDepartment(departmentName);
        }
        
        public System.Threading.Tasks.Task<bool> AddDepartmentAsync(string departmentName) {
            return base.Channel.AddDepartmentAsync(departmentName);
        }
        
        public void AddPromo(string promoName, string promoDept) {
            base.Channel.AddPromo(promoName, promoDept);
        }
        
        public System.Threading.Tasks.Task AddPromoAsync(string promoName, string promoDept) {
            return base.Channel.AddPromoAsync(promoName, promoDept);
        }
        
        public void AddStudent(string studentFirstName, string studentLastName, System.DateTime studentBirthDate, string promoName) {
            base.Channel.AddStudent(studentFirstName, studentLastName, studentBirthDate, promoName);
        }
        
        public System.Threading.Tasks.Task AddStudentAsync(string studentFirstName, string studentLastName, System.DateTime studentBirthDate, string promoName) {
            return base.Channel.AddStudentAsync(studentFirstName, studentLastName, studentBirthDate, promoName);
        }
        
        public string[] UpdatePromoLists() {
            return base.Channel.UpdatePromoLists();
        }
        
        public System.Threading.Tasks.Task<string[]> UpdatePromoListsAsync() {
            return base.Channel.UpdatePromoListsAsync();
        }
        
        public string[] UpdateDeptLists() {
            return base.Channel.UpdateDeptLists();
        }
        
        public System.Threading.Tasks.Task<string[]> UpdateDeptListsAsync() {
            return base.Channel.UpdateDeptListsAsync();
        }
    }
}
