//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppCliente_WebServiceIUT.ServiceSearch {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Student", Namespace="http://schemas.datacontract.org/2004/07/WebService_IUT.DataContracts")]
    [System.SerializableAttribute()]
    public partial class Student : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StudentDateBirthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StudentFirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StudentLastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StudentPromoNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StudentDateBirth {
            get {
                return this.StudentDateBirthField;
            }
            set {
                if ((object.ReferenceEquals(this.StudentDateBirthField, value) != true)) {
                    this.StudentDateBirthField = value;
                    this.RaisePropertyChanged("StudentDateBirth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StudentFirstName {
            get {
                return this.StudentFirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.StudentFirstNameField, value) != true)) {
                    this.StudentFirstNameField = value;
                    this.RaisePropertyChanged("StudentFirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StudentLastName {
            get {
                return this.StudentLastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.StudentLastNameField, value) != true)) {
                    this.StudentLastNameField = value;
                    this.RaisePropertyChanged("StudentLastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StudentPromoName {
            get {
                return this.StudentPromoNameField;
            }
            set {
                if ((object.ReferenceEquals(this.StudentPromoNameField, value) != true)) {
                    this.StudentPromoNameField = value;
                    this.RaisePropertyChanged("StudentPromoName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceSearch.ISearch")]
    public interface ISearch {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearch/SearchStudents", ReplyAction="http://tempuri.org/ISearch/SearchStudentsResponse")]
        AppCliente_WebServiceIUT.ServiceSearch.Student[] SearchStudents(string studentToSearch);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearch/SearchStudents", ReplyAction="http://tempuri.org/ISearch/SearchStudentsResponse")]
        System.Threading.Tasks.Task<AppCliente_WebServiceIUT.ServiceSearch.Student[]> SearchStudentsAsync(string studentToSearch);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearch/EditStudent", ReplyAction="http://tempuri.org/ISearch/EditStudentResponse")]
        void EditStudent(string oldStudentInfos, string studentFirstName, string studentLastName, string studentBirthDate, string studentPromo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearch/EditStudent", ReplyAction="http://tempuri.org/ISearch/EditStudentResponse")]
        System.Threading.Tasks.Task EditStudentAsync(string oldStudentInfos, string studentFirstName, string studentLastName, string studentBirthDate, string studentPromo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISearchChannel : AppCliente_WebServiceIUT.ServiceSearch.ISearch, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SearchClient : System.ServiceModel.ClientBase<AppCliente_WebServiceIUT.ServiceSearch.ISearch>, AppCliente_WebServiceIUT.ServiceSearch.ISearch {
        
        public SearchClient() {
        }
        
        public SearchClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SearchClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SearchClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SearchClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public AppCliente_WebServiceIUT.ServiceSearch.Student[] SearchStudents(string studentToSearch) {
            return base.Channel.SearchStudents(studentToSearch);
        }
        
        public System.Threading.Tasks.Task<AppCliente_WebServiceIUT.ServiceSearch.Student[]> SearchStudentsAsync(string studentToSearch) {
            return base.Channel.SearchStudentsAsync(studentToSearch);
        }
        
        public void EditStudent(string oldStudentInfos, string studentFirstName, string studentLastName, string studentBirthDate, string studentPromo) {
            base.Channel.EditStudent(oldStudentInfos, studentFirstName, studentLastName, studentBirthDate, studentPromo);
        }
        
        public System.Threading.Tasks.Task EditStudentAsync(string oldStudentInfos, string studentFirstName, string studentLastName, string studentBirthDate, string studentPromo) {
            return base.Channel.EditStudentAsync(oldStudentInfos, studentFirstName, studentLastName, studentBirthDate, studentPromo);
        }
    }
}
